### ISSUE TITLE
Nginx 1.15.3 + hpack errors

### ISSUE THREAD

**Issue by centminmod** [hakasenyang/openssl-patch#2]
Just a heads up with Nginx 1.15.3 master branch, HPACK patch will break again it seems

```
ccache gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g -I/usr/local/include -m64 -march=native -DTCP_FASTOPEN=23 -g -O3 -Wno-error=strict-aliasing -fstack-protector-strong -flto -fuse-ld=gold --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wimplicit-fallthrough=0 -fcode-hoisting  -Wp,-D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations -gsplit-dwarf -Wno-deprecated-declarations -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/local/include -I ../ngx_devel_kit-0.3.0/objs -I objs/addon/ndk -I ../ngx_devel_kit-0.3.0/src -I ../ngx_devel_kit-0.3.0/objs -I objs/addon/ndk -I ../pcre-8.42 -I ../openssl-tls1.3/.openssl/include -I ../zlib-cloudflare-1.3.0 -I objs -I src/http -I src/http/modules -I src/http/v2 -I ../ngx_devel_kit-0.3.0/src \
        -o objs/src/http/modules/ngx_http_index_module.o \
        src/http/modules/ngx_http_index_module.c
src/http/v2/ngx_http_v2.c: In function ‘ngx_http_v2_state_settings_params’:
src/http/v2/ngx_http_v2.c:2083:9: error: duplicate case value
         case NGX_HTTP_V2_HEADER_TABLE_SIZE_SETTING:
         ^~~~
src/http/v2/ngx_http_v2.c:2078:9: note: previously used here
         case NGX_HTTP_V2_HEADER_TABLE_SIZE_SETTING:
         ^~~~
make[1]: *** [objs/src/http/v2/ngx_http_v2.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/svr-setup/nginx-master'
make: *** [build] Error 2
```

**Comment by hakasenyang** [comment]
Hello.

Use this patch : https://github.com/hakasenyang/openssl-patch/blob/master/nginx_hpack_push_1.15.3.patch

Test site : https://test.hakase.io/

**Comment by centminmod** [comment]
Thanks @hakasenyang that was quick. Seems to be now working with Nginx 1.15.3 master branch

```
url=https://http2.domain.com
for i in $(seq 1 20); do echo "h2load run $i"; h2load $url -n $i | tail -6 | head -1; done  
h2load run 1
traffic: 6.69KB (6849) total, 190B (190) headers (space savings 36.03%), 6.44KB (6592) data
h2load run 2
traffic: 13.16KB (13471) total, 202B (202) headers (space savings 65.99%), 12.88KB (13184) data
h2load run 3
traffic: 19.62KB (20093) total, 214B (214) headers (space savings 75.98%), 19.31KB (19776) data
h2load run 4
traffic: 26.09KB (26715) total, 226B (226) headers (space savings 80.98%), 25.75KB (26368) data
h2load run 5
traffic: 32.56KB (33337) total, 238B (238) headers (space savings 83.97%), 32.19KB (32960) data
h2load run 6
traffic: 39.02KB (39959) total, 250B (250) headers (space savings 85.97%), 38.63KB (39552) data
h2load run 7
traffic: 45.49KB (46581) total, 262B (262) headers (space savings 87.40%), 45.06KB (46144) data
h2load run 8
traffic: 51.96KB (53203) total, 274B (274) headers (space savings 88.47%), 51.50KB (52736) data
h2load run 9
traffic: 58.42KB (59825) total, 286B (286) headers (space savings 89.30%), 57.94KB (59328) data
h2load run 10
traffic: 64.89KB (66447) total, 298B (298) headers (space savings 89.97%), 64.38KB (65920) data
h2load run 11
traffic: 71.36KB (73069) total, 310B (310) headers (space savings 90.51%), 70.81KB (72512) data
h2load run 12
traffic: 77.82KB (79691) total, 322B (322) headers (space savings 90.97%), 77.25KB (79104) data
h2load run 13
traffic: 84.29KB (86313) total, 334B (334) headers (space savings 91.35%), 83.69KB (85696) data
h2load run 14
traffic: 90.76KB (92935) total, 346B (346) headers (space savings 91.68%), 90.13KB (92288) data
h2load run 15
traffic: 97.22KB (99557) total, 358B (358) headers (space savings 91.96%), 96.56KB (98880) data
h2load run 16
traffic: 103.69KB (106179) total, 370B (370) headers (space savings 92.21%), 103.00KB (105472) data
h2load run 17
traffic: 110.16KB (112801) total, 382B (382) headers (space savings 92.43%), 109.44KB (112064) data
h2load run 18
traffic: 116.62KB (119423) total, 394B (394) headers (space savings 92.63%), 115.88KB (118656) data
h2load run 19
traffic: 123.09KB (126045) total, 406B (406) headers (space savings 92.81%), 122.31KB (125248) data
h2load run 20
traffic: 129.56KB (132667) total, 418B (418) headers (space savings 92.96%), 128.75KB (131840) data
```

```
nginx -V
nginx version: nginx/1.15.3 (160818-075438)
built by gcc 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC) 
built with OpenSSL 1.1.0i  14 Aug 2018
TLS SNI support enabled
```
> configure arguments: --with-ld-opt='-L/usr/local/lib -ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-I/usr/local/include -m64 -march=native -DTCP_FASTOPEN=23 -g -O3 -Wno-error=strict-aliasing -fstack-protector-strong -flto -fuse-ld=gold --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wimplicit-fallthrough=0 -fcode-hoisting -Wp,-D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations -gsplit-dwarf' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --build=160818-075438 --with-compat --with-http_stub_status_module --with-http_secure_link_module --with-libatomic --with-http_gzip_static_module --add-dynamic-module=../ngx_brotli --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module --with-stream_geoip_module --with-stream_realip_module --with-stream_ssl_preread_module --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_realip_module --add-dynamic-module=../ngx-fancyindex-0.4.2 --add-module=../ngx_cache_purge-2.4.2 --add-dynamic-module=../ngx_devel_kit-0.3.0 --add-dynamic-module=../set-misc-nginx-module-0.32 --add-dynamic-module=../echo-nginx-module-0.61 --add-module=../redis2-nginx-module-0.15 --add-module=../ngx_http_redis-0.3.7 --add-module=../memc-nginx-module-0.18 --add-module=../srcache-nginx-module-0.31 --add-dynamic-module=../headers-more-nginx-module-0.33 --with-pcre=../pcre-8.42 --with-pcre-jit --with-zlib=../zlib-cloudflare-1.3.0 --with-http_ssl_module --with-http_v2_module --with-http_v2_hpack_enc --with-openssl=../openssl-1.1.0i --with-openssl-opt='enable-ec_nistp_64_gcc_128'

**Comment by hakasenyang** [comment]
This is currently being applied to my site as well, and it works fine.

```
root@hakase:~# url=https://hakase.io
root@hakase:~# for i in $(seq 1 20); do echo "h2load run $i"; h2load $url -n $i | tail -6 | head -1; done
h2load run 1
traffic: 2.96KB (3028) total, 580B (580) headers (space savings 28.57%), 2.33KB (2381) data
h2load run 2
traffic: 5.32KB (5443) total, 596B (596) headers (space savings 63.30%), 4.65KB (4762) data
h2load run 3
traffic: 7.67KB (7858) total, 612B (612) headers (space savings 74.88%), 6.98KB (7143) data
h2load run 4
traffic: 10.03KB (10273) total, 628B (628) headers (space savings 80.67%), 9.30KB (9524) data
h2load run 5
traffic: 12.39KB (12688) total, 644B (644) headers (space savings 84.14%), 11.63KB (11905) data
h2load run 6
traffic: 14.75KB (15103) total, 660B (660) headers (space savings 86.45%), 13.95KB (14286) data
h2load run 7
traffic: 17.11KB (17518) total, 676B (676) headers (space savings 88.11%), 16.28KB (16667) data
h2load run 8
traffic: 19.47KB (19933) total, 692B (692) headers (space savings 89.35%), 18.60KB (19048) data
h2load run 9
traffic: 21.82KB (22348) total, 708B (708) headers (space savings 90.31%), 20.93KB (21429) data
h2load run 10
traffic: 24.18KB (24763) total, 724B (724) headers (space savings 91.08%), 23.25KB (23810) data
h2load run 11
traffic: 26.54KB (27178) total, 740B (740) headers (space savings 91.72%), 25.58KB (26191) data
h2load run 12
traffic: 28.90KB (29593) total, 756B (756) headers (space savings 92.24%), 27.90KB (28572) data
h2load run 13
traffic: 31.26KB (32008) total, 772B (772) headers (space savings 92.69%), 30.23KB (30953) data
h2load run 14
traffic: 33.62KB (34423) total, 788B (788) headers (space savings 93.07%), 32.55KB (33334) data
h2load run 15
traffic: 35.97KB (36838) total, 804B (804) headers (space savings 93.40%), 34.88KB (35715) data
h2load run 16
traffic: 38.33KB (39253) total, 820B (820) headers (space savings 93.69%), 37.20KB (38096) data
h2load run 17
traffic: 40.69KB (41668) total, 836B (836) headers (space savings 93.94%), 39.53KB (40477) data
h2load run 18
traffic: 43.05KB (44083) total, 852B (852) headers (space savings 94.17%), 41.85KB (42858) data
h2load run 19
traffic: 45.41KB (46498) total, 868B (868) headers (space savings 94.37%), 44.18KB (45239) data
h2load run 20
traffic: 47.77KB (48913) total, 884B (884) headers (space savings 94.56%), 46.50KB (47620) data
```

I think the issue is resolved, and I will close the issue.

**Comment by kevin25** [comment]
I can't compile with zlib of cloudflare 

> make[2]: Entering directory '/tmp/boring-nginx/nginx/nginx-1.15.3/modules/zlib'
make[2]: *** No rule to make target 'distclean'.  Stop.
make[2]: Leaving directory '/tmp/boring-nginx/nginx/nginx-1.15.3/modules/zlib'
objs/Makefile:1435: recipe for target 'modules/zlib//libz.a' failed
make[1]: *** [modules/zlib//libz.a] Error 2
make[1]: Leaving directory '/tmp/boring-nginx/nginx/nginx-1.15.3'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by hakasenyang** [comment]
@kevin25 Cloudflare's zlib only support "x64" cpu.
Please give the information by typing the following command.
cat /proc/cpuinfo

**Comment by kevin25** [comment]
It should be 64

`3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux`

**Comment by hakasenyang** [comment]
Use this commands.

```sh
cd /tmp/boring-nginx/nginx/nginx-1.15.3/modules/zlib
./configure
cd ../..
```

And retry build.

**Comment by kevin25** [comment]
@hakasenyang It works. Thank you

**Comment by kevin25** [comment]
my openssl is too old due to old debian OS. Which configuration is good for it?

`OpenSSL 1.0.1t`

`ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
ssl_ciphers [Copy it from below and paste it here.];
ssl_ecdh_curve X25519:P-256:P-384;
ssl_prefer_server_ciphers on;`

**Comment by hakasenyang** [comment]
You can not use Equal Preference, which is built into BoringSSL.

TLS 1.3 is supported starting with OpenSSL-1.1.1.

It is safe to use:
```
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers EECDH+ECDSA+AESGCM+AES128:EECDH+ECDSA+AESGCM+AES256:EECDH+ECDSA+AES128+SHA:EECDH+ECDSA+AES256+SHA:EECDH+aRSA+AESGCM+AES128:EECDH+aRSA+AESGCM+AES256:EECDH+aRSA+AES128+SHA:EECDH+aRSA+AES256+SHA:RSA+AES128+SHA:RSA+AES256+SHA:RSA+3DES;
ssl_ecdh_curve X25519:P-256:P-384;
ssl_prefer_server_ciphers on;
```

**Comment by kevin25** [comment]
Thank you. I can't use ssl_ecdh_curve X25519:P-256:P-384; either. Do you think manually upgrade OpenSSL will work?

**Comment by hakasenyang** [comment]
Yes. [Read my tutorial](https://github.com/hakasenyang/openssl-patch#openssl-patch-1).

Use --with-openssl for the nginx configuration.

**Comment by kevin25** [comment]
It seems to work. Thank you!

**Comment by hakasenyang** [comment]
The issue has been resolved, so we will close the issue.

**Comment by kevin25** [comment]
Any update for Nginx 1.16.1?
